# Simulation parameters for IRM ATE Coverage

simulation_parameters:
  repetitions: 200
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [1.0] # Treatment effect
  n_obs: [2000] # Sample size
  dim_x: [20] # Number of covariates

# Define reusable learner configurations
learner_definitions:
  lgbmr: &lgbmr
    name: "LGBM Regr."

  lgbmc: &lgbmc
    name: "LGBM Clas."

dml_parameters:
  learners:
    - ml_g: *lgbmr
      ml_m: *lgbmc
      ml_pi: *lgbmc


confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
