# Simulation parameters for PLR ATE Coverage

simulation_parameters:
  repetitions: 100
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [1.0] # Treatment effect
  n: [25] # first cluster dimension
  m: [25] # second cluster dimension
  dim_X: [10] # Number of covariates

# Define reusable learner configurations
learner_definitions:
  linear: &linear
    name: "Linear"

  lgbm: &lgbm
    name: "LGBM Regr."
    params:
      n_estimators: 500
      learning_rate: 0.01

dml_parameters:
  # ML methods for ml_g and ml_m
  learners:
    - ml_g: *linear
      ml_m: *linear
      ml_r: *linear
    - ml_g: *lgbm
      ml_m: *lgbm
      ml_r: *lgbm
    - ml_g: *linear
      ml_m: *lgbm
      ml_r: *lgbm
    - ml_g: *lgbm
      ml_m: *linear
      ml_r: *lgbm
    - ml_g: *lgbm
      ml_m: *lgbm
      ml_r: *linear
    - ml_g: *linear
      ml_m: *linear
      ml_r: *lgbm
    - ml_g: *lgbm
      ml_m: *linear
      ml_r: *linear
    - ml_g: *linear
      ml_m: *lgbm
      ml_r: *linear

  score: ["partialling out", "IV-type"]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
