# Simulation parameters for PLR ATE Coverage

simulation_parameters:
  repetitions: 100
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [500] # Sample size
  dim_x: [20] # Number of covariates

# Define reusable learner configurations
learner_definitions:
  lgbm: &lgbm
    name: "LGBM Regr."

dml_parameters:
  learners:
    - ml_g: *lgbm
      ml_m: *lgbm


  score: ["partialling out"]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
