project:
  type: website
  output-dir: _site/dev

metadata-files:
  - _website.yml

website:
  site-url: https://docs.doubleml.org/doubleml-coverage/dev/
  drafts:
    - index.qmd
    # IRM
    - irm/irm.qmd
    - irm/irm_gate.qmd
    - irm/irm_cate.qmd
    - irm/apo.qmd
    - irm/qte.qmd
    - irm/iivm.qmd
    # PLM
    - plm/plr.qmd
    - plm/plr_gate.qmd
    - plm/plr_cate.qmd
    - plm/lplr.qmd
    - plm/plpr.qmd
    - plm/pliv.qmd
    # DID
    - did/did_pa.qmd
    - did/did_cs.qmd
    # SSM
    - ssm/ssm_mar.qmd
    - ssm/ssm_nonignorable.qmd
    # RDD
    - rdd/rdd.qmd
  draft-mode: visible
