# Simulation parameters for DID Multi Coverage

simulation_parameters:
  repetitions: 100
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  DGP: [1, 4] # Different DGP specifications
  n_obs: [1000] # Sample size for each simulation (has to be a list)

# Define reusable learner configurations
learner_definitions:
  lgbmr: &lgbmr
    name: "LGBM Regr."

  lgbmc: &lgbmc
    name: "LGBM Clas."


dml_parameters:
  # ML methods for ml_g and ml_m
  learners:
    - ml_g: *lgbmr
      ml_m: *lgbmc

  control_group:
    - "never_treated" # Control group specification

  score:
    - observational # Standard DML score

  in_sample_normalization: [true]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
