# Simulation parameters for APOS Coverage

simulation_parameters:
  repetitions: 200
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  n_obs: [500] # Sample size
  n_levels: [2]
  linear: [True]

# Define reusable learner configurations
learner_definitions:
  lgbmr: &lgbmr
    name: "LGBM Regr."


  lgbmc: &lgbmc
    name: "LGBM Clas."

dml_parameters:
  treatment_levels: [[0, 1, 2]]
  trimming_threshold: [0.01]
  learners:
    - ml_g: *lgbmr
      ml_m: *lgbmc



confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
