# Simulation parameters for IRM ATE Coverage with Tuning

simulation_parameters:
  repetitions: 100
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [1000] # Sample size
  dim_x: [5] # Number of covariates

# Define reusable learner configurations
learner_definitions:
  lgbmr: &lgbmr
    name: "LGBM Regr."

  lgbmc: &lgbmc
    name: "LGBM Clas."

dml_parameters:
  learners:
    - ml_g: *lgbmr
      ml_m: *lgbmc


confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
